name: Check
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          cache: npm
      - run: npm ci
      - run: npm test
      - run: cd examples && npm ci
      - run: cd fuzz && npm ci && npm run compile
      - run: npm run lint
      - run: npm run check-format
